# Generated by Django 4.0.6 on 2022-08-02 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('start_time', models.DateTimeField(verbose_name='Время начала')),
                ('finish_time', models.DateTimeField(verbose_name='Время окончания мероприятия')),
                ('description', models.TextField(blank=True, verbose_name='Описание мероприятия')),
            ],
            options={
                'verbose_name': 'Мероприятие',
                'verbose_name_plural': 'Мероприятия',
            },
        ),
    ]
