# Generated by Django 4.0.6 on 2022-08-02 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_nick', models.CharField(max_length=50, verbose_name='Ник в Телеграм')),
                ('chat_id', models.CharField(blank=True, max_length=50, verbose_name='Id для бота')),
                ('tg_state', models.CharField(default='start', max_length=50, verbose_name='Состояние бота')),
                ('firstname', models.CharField(blank=True, max_length=50, verbose_name='Имя')),
                ('second_name', models.CharField(blank=True, max_length=50, verbose_name='Фамилия')),
                ('company', models.CharField(blank=True, max_length=100, verbose_name='Компания')),
                ('position', models.CharField(blank=True, max_length=100, verbose_name='Должность')),
                ('status', models.CharField(choices=[('PARTICIPANT', 'Участник'), ('SPEAKER', 'Спикер')], default='PARTICIPANT', max_length=50, verbose_name='Статус')),
                ('networking', models.BooleanField(default=False, verbose_name='Готов к нетворкингу')),
            ],
            options={
                'verbose_name': ('Участник',),
                'verbose_name_plural': 'Участники',
            },
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='event',
            name='finish_time',
            field=models.DateTimeField(verbose_name='Время окончания'),
        ),
        migrations.AddField(
            model_name='event',
            name='speaker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='meetup.user', verbose_name='Спикер'),
        ),
    ]
