# Generated by Django 4.0.6 on 2022-08-02 18:21

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0002_user_alter_event_description_alter_event_finish_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, verbose_name='Текст вопроса')),
                ('ask_time', models.DateTimeField(default=datetime.datetime(2022, 8, 2, 18, 21, 15, 850658, tzinfo=utc), verbose_name='Время создания')),
                ('answered', models.BooleanField(default=False, verbose_name='Отвечен')),
                ('answerer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions_to', to='meetup.user', verbose_name='Кому')),
                ('asker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions_from', to='meetup.user', verbose_name='От кого')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
            },
        ),
        migrations.CreateModel(
            name='Donut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Сумма доната')),
                ('time', models.DateTimeField(default=datetime.datetime(2022, 8, 2, 18, 21, 15, 851661, tzinfo=utc), verbose_name='Время доната')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donuts', to='meetup.user', verbose_name='Кто донатил')),
            ],
            options={
                'verbose_name': 'Донат',
                'verbose_name_plural': 'Донаты',
            },
        ),
    ]
