# Generated by Django 4.0.6 on 2022-08-03 12:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0004_user_email_alter_donut_time_alter_question_ask_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='second_name',
            new_name='lastname',
        ),
        migrations.AlterField(
            model_name='donut',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 3, 12, 38, 14, 797485, tzinfo=utc), verbose_name='Время доната'),
        ),
        migrations.AlterField(
            model_name='question',
            name='ask_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 3, 12, 38, 14, 797485, tzinfo=utc), verbose_name='Время создания'),
        ),
    ]
