# Generated by Django 4.0.6 on 2022-08-04 09:39

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0005_rename_second_name_user_lastname_alter_donut_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Сумма доната')),
                ('time', models.DateTimeField(default=datetime.datetime(2022, 8, 4, 9, 39, 23, 142505, tzinfo=utc), verbose_name='Время доната')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donates', to='meetup.user', verbose_name='Кто донатил')),
            ],
            options={
                'verbose_name': 'Донат',
                'verbose_name_plural': 'Донаты',
            },
        ),
        migrations.AlterField(
            model_name='question',
            name='ask_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 4, 9, 39, 23, 141676, tzinfo=utc), verbose_name='Время создания'),
        ),
        migrations.DeleteModel(
            name='Donut',
        ),
    ]
