# Generated by Django 4.0.6 on 2022-08-04 07:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0006_user_info_alter_donut_time_alter_question_ask_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answer',
            field=models.TextField(blank=True, verbose_name='Ответ'),
        ),
        migrations.AlterField(
            model_name='donut',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 4, 7, 44, 39, 480104, tzinfo=utc), verbose_name='Время доната'),
        ),
        migrations.AlterField(
            model_name='question',
            name='ask_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 4, 7, 44, 39, 480104, tzinfo=utc), verbose_name='Время создания'),
        ),
    ]
