# Generated by Django 4.0.6 on 2022-08-05 06:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0009_donate_alter_question_answer_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donate',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 5, 6, 59, 35, 977040, tzinfo=utc), verbose_name='Время доната'),
        ),
        migrations.AlterField(
            model_name='question',
            name='ask_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 5, 6, 59, 35, 977040, tzinfo=utc), verbose_name='Время создания'),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, verbose_name='Текст сообщения')),
                ('time_created', models.DateTimeField(default=datetime.datetime(2022, 8, 5, 6, 59, 35, 978040, tzinfo=utc), verbose_name='Время создания')),
                ('to_send', models.BooleanField(default=False, verbose_name='Предназначено для отправки')),
                ('targets', models.ManyToManyField(null=True, to='meetup.user', verbose_name='Адресаты для рассылки')),
            ],
        ),
    ]
