# Generated by Django 4.0.6 on 2022-08-05 08:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0010_alter_donate_time_alter_question_ask_time_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'verbose_name': 'Сообщение', 'verbose_name_plural': 'Сообщения'},
        ),
        migrations.RemoveField(
            model_name='message',
            name='time_created',
        ),
        migrations.AddField(
            model_name='message',
            name='time_sent',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='donate',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 5, 8, 13, 56, 567402, tzinfo=utc), verbose_name='Время доната'),
        ),
        migrations.AlterField(
            model_name='question',
            name='ask_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 5, 8, 13, 56, 566405, tzinfo=utc), verbose_name='Время создания'),
        ),
    ]
